name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project_dir:
          - 01_hello
          - 02_echor
          - 03_catr
          - 04_headr
          - 05_wcr
          - 06_uniqr
          - 07_findr
          - 08_cutr
          - 09_grepr
          - 10_commr
          - 11_tailr
          - 12_fortuner
    defaults:
      run:
        working-directory: ${{ matrix.project_dir }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: rustfmt, clippy
      - run: ./ci.sh
      - run: cargo check
      - run: cargo fmt --all -- --check
      - run: cargo clippy -- -D warnings
      - run: cargo test
