name: Pipeline

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  pipeline:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: rustfmt, clippy
      - run: |
          ./install-dependencies.sh
      - run: |
          ./check-all.sh
          ./test-all.sh
